### ISSUE TITLE
put.js behaves slow(10s+)

### ISSUE THREAD

**Issue by marko999** [muratcorlu/connect-api-mocker#22] opened 2018-07-06 16:13 UTC
Under agreement folder that is properly mapped with connect-api-mocker and webpack, I have one dynamic response, post and put...something like this:

- agreement
  - `__agreementId__`
    - GET.js
  - POST.js
  - PUT.js

Everything works fine but for some reason mapping of the `PUT.js` is too slow, it takes sometime more than 10s for server to respond...I am saying on purpose `mapping` because I have added logs into a put function and they are not even hit for that 10s, so process before it is taking it too long, not sure why...

any ideas?

p.s. also I have tried to remove everything we have in put and directly return 204, still same behavior

**Comment by muratcorlu** [comment] 2018-07-06 20:37
Hi @marko999,

Can you share your webpack config and PUT.js file contents? So we can try reproducing the problem.

**Comment by muratcorlu** [comment] 2018-12-07 14:43
I'm closing this because of unclarity.

**Closed by muratcorlu** 2018-12-07 14:43 UTC
